version: '3'

interactive: true

dotenv: ['.env']

tasks:
  wp:
    desc: Run a WP-CLI command
    cmds:
      - docker compose run --rm wpcli wp {{.CLI_ARGS}}

  setup:
    desc: Initialize the local WordPress installation
    requires:
      vars:
        - name: VITE_DEBUG
          enum: [enable, disable]
    cmds:
      - task: wp
        vars:
          CLI_ARGS: core install --url=http://localhost --title="$WP_TITLE" --admin_user=$WP_USER --admin_password=$WP_PASS --admin_email=$WP_EMAIL --skip-email
      - task: wp
        vars:
          CLI_ARGS: plugin install woocommerce --version=10.5.2
      - task: wp
        vars:
          CLI_ARGS: plugin activate woocommerce
      - task: wp
        vars:
          CLI_ARGS: plugin activate wc-recurring-pdf
      - task: wp
        vars:
          CLI_ARGS: post create --post_type=page --post_title="Legacy Cart" --post_content="[woocommerce_cart]" --post_status=publish
      - task: wp
        vars:
          CLI_ARGS: post create --post_type=page --post_title="Legacy Checkout" --post_content="[woocommerce_checkout]" --post_status=publish
