<?php

namespace WcRecurring\Menu;

use WcRecurring\Model\Placeholder\CompanyDetails;
use WcRecurring\Model\InvoiceList;
use WcRecurring\Model\Invoice;

use WcRecurring\WcRecurringIndex;

class InvoiceMenu
{
    public function __construct()
    {
        if (defined('DOING_AJAX') && DOING_AJAX) {
            return;
        }
        
        if (is_admin()) {
            add_action('admin_menu', array( $this, 'admin_menu' ));
        }

        foreach (['general', 'invoice', 'email', 'export'] as $section) {
            add_action('admin_post_wc_recurring_save_' . $section, [$this, 'saveSettingsSection']);
        }
    }

    public function admin_menu()
    {
        add_menu_page('WC-' . __('Invoices', 'wc-invoice-pdf'), 'WC-' . __('Invoices', 'wc-invoice-pdf'), 'null', 'wcinvoicepdf_menu', null, WCRECURRING_PLUGIN_URL.'invoicepdf.png', 3);
        add_submenu_page('wcinvoicepdf_menu', __('Invoices', 'wc-invoice-pdf'), __('Invoices', 'wc-invoice-pdf'), 'edit_themes', 'wcinvoicepdf_invoices', [$this, 'DisplayInvoices']);
        add_submenu_page('wcinvoicepdf_menu', __('Settings'), __('Settings'), 'edit_themes', 'wcinvoicepdf_settings', [$this, 'DisplaySettingsVue']);
        // hide the menu using null
        add_submenu_page(null, '_Invoice', '_Invoice', 'wc_invoice_pdf', 'wcinvoicepdf_invoice', [$this, 'OpenInvoice']);
    }

    /**
     * Check for permission on specific invoices being generated by the sytem and populated to users "My Account" page.
     * Also it validates the access for administrative users to generate invoices/quotes
     */
    private function userHasAccess($invoice)
    {
        global $current_user;
        
        // only for logged in users
        if (!is_user_logged_in()) {
            return false;
        }

        if (!current_user_can('manage_options') && $invoice->customer_id != $current_user->ID) {
            return false;
        }

        return true;
    }

    /**
     * Used to open or generate invoices.
     * This method is also used in front end through "My Account" endpoint
     */
    public function OpenInvoice()
    {
        // remove previous output to generate a clean pdf result
        ob_clean();

        $offer = !empty($_GET['offer']) ? true : false;

        if (!empty($_GET['order'])) {
            $order = new \WC_Order(intval($_GET['order']));

            $invoice = new Invoice($order);

            //$invoicepdf = new InvoicePdf();

            if (!$this->userHasAccess($invoice)) {
                wp_die("You do not have access to generate invoices");
            }

            $invoice->makeNew($offer);

            header("Content-type: application/pdf");
            header("Content-Disposition: inline; filename=". ($offer ? $invoice->offer_number : $invoice->invoice_number) .'.pdf');

            echo $invoice->document;
        } elseif (!empty($_GET['invoice'])) {
            $invoice = new Invoice(intval($_GET['invoice']));

            if (!$invoice->ID) {
                wp_die(__('Invoice not found our no access to this resource', 'wc-invoice-pdf'));
            }

            if (!$this->userHasAccess($invoice)) {
                wp_die(__('Invoice not found our no access to this resource', 'wc-invoice-pdf'));
            }

            if (!empty($_GET['xml'])) {
                header("Content-type: application/xml");
                header("Content-Disposition: attachment; filename=".$invoice->invoice_number .'.xml');
    
                echo $invoice->xinvoice;
            } else {
                header("Content-type: application/pdf");
                header("Content-Disposition: inline; filename=".$invoice->invoice_number .'.pdf');
    
                echo $invoice->document;
            }
        }

        die;
    }

    /**
     * Display a list of all available invoices
     */
    public function DisplayInvoices()
    {
        global $wpdb;
        $invList = new InvoiceList();
        
        $a = $invList->current_action();
        $invList->prepare_items();

        // get the invoice_reminder cron job installed by this plugin
        $cron_jobs = get_option('cron');
        $invoice_reminder_event = array_filter($cron_jobs, function ($v) {
            return isset($v['invoice_reminder']);
        });

        $isInvoiceSubmissionEnabled = WcRecurringIndex::$OPTIONS['wc_recur'];

        ?>
        <div class='wrap'>
            <h1><?php _e('Invoices', 'wc-invoice-pdf') ?></h1>
            <?php if (count($invoice_reminder_event) > 0 && $isInvoiceSubmissionEnabled) :
                $event_time = key($invoice_reminder_event);

                $d = new \DateTime();
                $d->setTimezone(new \DateTimeZone(get_option('timezone_string', 'UTC') ?: 'UTC'));
                $d->setTimestamp($event_time);
                ?>
            <div class="updated"><p><?php printf(__('The next automated invoice submission is scheduled for %s', 'wc-invoice-pdf'), $d->format('Y-m-d H:i')); ?></p></div>
            <?php endif; ?>
            <?php if (!$isInvoiceSubmissionEnabled) : ?>
            <div class="error"><p><?php _e("The scheduler is disabled for automated invoice submission. Please check the <a href='/wp-admin/admin.php?page=wcinvoicepdf_settings'>settings</a>", 'wc-invoice-pdf') ?></p></div>
            <?php endif; ?>
            <h2></h2>
            <form action="" method="GET">
                <input type="hidden" name="page" value="<?php echo esc_attr($_REQUEST['page']) ?>" />
                <input type="hidden" name="action" value="filter" />
                <label class="post-attributes-label" for="user_login"><?php _e('Customer', 'woocommerce') ?></label>
                <select name="customer_id" style="min-width: 200px">
                    <option value=""></option>
                <?php
                $users = get_users(['role' => 'customer']);
                foreach ($users as $u) {
                    $company = get_user_meta($u->ID, 'billing_company', true);
                    $selected = (isset($_GET['customer_id']) && $u->ID == intval($_GET['customer_id']))?'selected':'';
                    echo '<option value="'.$u->ID.'" '.$selected.'>'. $company . ' (' .$u->user_login.')</option>';
                }
                ?>
                </select>
                <input type="checkbox" id="recur_only" name="recur_only" value="1" <?php echo (!empty($_GET['recur_only'])?'checked':'') ?> /> <label for="recur_only"><?php _e('Recurring payments', 'wc-invoice-pdf') ?></label>
                <input type="submit" class="button" value="<?php _e('Filter &#187;') ?>">
            </form>
            <form action="" method="POST">
                <div style="margin-top: 1em">
                    <?php if (isset($_GET['post_status'])) : ?>
                        <a href="/wp-admin/admin.php?page=wcinvoicepdf_invoices"><?php _e('All') ?></a>
                    <?php else : ?>
                        <?php _e('All') ?>
                    <?php endif; ?>
                    |
                    <?php if (!isset($_GET['post_status'])) : ?>
                        <a href="<?php echo '?' . $_SERVER['QUERY_STRING'] . '&post_status=deleted'; ?>"><?php printf(__('Trash <span class="count">(%s)</span>'), $invList->total_trash_rows) ?></a>
                    <?php else : ?>
                        <?php printf(__('Trash <span class="count">(%s)</span>'), $invList->total_trash_rows) ?>
                    <?php endif; ?>
                </div>
                <?php $invList->display(); ?>
            </form>
        </div>
        <?php
    }

    /**
     * Render the Vue-based settings application.
     */
    public function DisplaySettingsVue()
    {
        wp_enqueue_media();
        $config = $this->getSettingsConfig();
        ?>
        <div class="wrap wc-recurring-settings">
            <h1><?php _e('WC-Invoice Settings', 'wc-invoice-pdf'); ?></h1>
            <script type="application/json" id="wc-recurring-settings-data"><?php echo wp_json_encode($config); ?></script>
            <div id="wc-recurring-settings-app">
                <span>Loading...</span>
            </div>
            <noscript><?php _e('JavaScript is required to edit these settings.', 'wc-invoice-pdf'); ?></noscript>
        </div>
        <?php
    }

    private function getSettingsSections()
    {
        return [
            'general' => ['wc_company_name', 'wc_company_email', 'wc_company_vat', 'wc_invoice_due_days', 'wc_order_subscriptions', 'wc_mail_reminder', 'wc_mail_sender', 'wc_pdf_xinvoice', 'wc_order_show_completed', 'wc_customer_login_gdpr', 'wc_pdf_b2c', 'wc_recur_test', 'wc_payment_reminder', 'wc_recur', 'wc_recur_reminder', 'wc_recur_reminder_age', 'wc_recur_reminder_interval', 'wc_recur_reminder_max'],
            'invoice' => ['wc_pdf_title', 'wc_pdf_template', 'wc_pdf_condition', 'wc_pdf_condition_offer', 'wc_pdf_info'],
            'email' => ['wc_payment_message', 'wc_recur_message', 'wc_recur_reminder_message'],
            'export' => ['wc_export_locale', 'wc_export_notes', 'wc_export_account', 'wc_export_account_posted', 'wc_export_account_tax']
        ];
    }

    private function getSettingsConfig()
    {
        $company = CompanyDetails::getInstance();
        $endpoints = [];
        foreach ($this->getSettingsSections() as $section => $fields) {
            $endpoints[$section] = [
                'url' => admin_url('admin-post.php?action=wc_recurring_save_' . $section),
                'nonce' => wp_create_nonce('wc-recurring-settings-' . $section)
            ];
        }

        return [
            'options' => WcRecurringIndex::$OPTIONS,
            'subscriptions' => WcRecurringIndex::$SUBSCRIPTIONS,
            'sections' => $this->getSettingsSections(),
            'endpoints' => $endpoints,
            'companyAddress' => $company->getSingleAddress(),
            'scheduleActive' => (bool) wp_get_schedule('invoice_reminder'),
            'templateUrl' => WCRECURRING_PLUGIN_URL . 'resources/demo_invoice_template.docx',
            'woocommerceSettingsUrl' => admin_url('admin.php?page=wc-settings&tab=general')
        ];
    }

    public function saveSettingsSection()
    {
        if (!current_user_can('edit_themes')) {
            wp_die(__('You do not have permission to change these settings.', 'wc-invoice-pdf'));
        }

        $section = sanitize_key(wp_unslash($_GET['action'] ?? ''));
        $section = str_replace('wc_recurring_save_', '', $section);
        $sections = $this->getSettingsSections();
        if (!isset($sections[$section])) {
            wp_die(__('Invalid settings section.', 'wc-invoice-pdf'));
        }

        check_admin_referer('wc-recurring-settings-' . $section);
        $posted = array_intersect_key(wp_unslash($_POST), array_flip($sections[$section]));
        $checkboxes = ['wc_pdf_xinvoice', 'wc_order_show_completed', 'wc_customer_login_gdpr', 'wc_pdf_b2c', 'wc_recur_test', 'wc_payment_reminder', 'wc_recur', 'wc_recur_reminder'];
        foreach (array_intersect($checkboxes, $sections[$section]) as $checkbox) {
            $posted[$checkbox] = isset($posted[$checkbox]) ? 1 : 0;
        }

        WcRecurringIndex::$OPTIONS = array_replace(WcRecurringIndex::$OPTIONS, $posted);
        WcRecurringIndex::save_options();
        wp_send_json_success(['section' => $section]);
    }
}
