name: Generate Release Notes

on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install github-release-notes -g
    - name: Write PreRelease Notes
      env:
        GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gren release --override -P --tags=${{ github.event.ref }}
