name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install SVN ( Subversion )
        run: |
          sudo apt-get update
          sudo apt-get install subversion
      - run: composer remove --dev squizlabs/php_codesniffer
      - name: Install dependencies
        run: composer install --no-interaction --prefer-source
      - name: Run strauss
        run: composer prefix-namespaces
      - name: FIX ROSPDF includes and fonts
        run: cp -r vendor/rospdf/pdf-php/src/{include,fonts} vendor_build/rospdf/pdf-php/src/
      - name: Remove vendor
        run: rm -r vendor
      - run: composer dump-autoload
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wc-invoice-pdf
          ASSETS_DIR: assets
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
